"""
Helper module for ORCA-PI (OPI) integration.
Handles configuration of ORCA input parameters and generation of input files.

This follows the OPI tutorial patterns for proper enum-based configuration.
Reference: ORCA Python Interface (OPI) IR Spectrum Tutorial
"""

import logging
import os
from typing import Dict, Any, Optional
from pathlib import Path

# Try to import RDKit for molecular conversion
try:
    from rdkit import Chem
    from rdkit.Chem import AllChem
    RDKIT_AVAILABLE = True
except ImportError:
    RDKIT_AVAILABLE = False

# Try to import OPI with all enum classes from the tutorial
try:
    from opi.core import Calculator
    from opi.input.simple_keywords import (
        SimpleKeyword,
        Dft,
        Task,
        BasisSet,
        Approximation,
        AuxBasisSet,
        DispersionCorrection
    )
    from opi.input.blocks.block_cpcm import BlockCpcm
    from opi.input.blocks.block_freq import BlockFreq
    from opi.input.structures.structure import Structure
    OPI_AVAILABLE = True
except ImportError:
    OPI_AVAILABLE = False

from services.qc.config import QCConfig

logger = logging.getLogger(__name__)

def convert_to_simple_xyz(molecule_data: str) -> str:
    """
    Convert various molecular formats (PDB, SDF, MOL, SMILES) to simple XYZ format.
    
    Simple XYZ format:
    <number of atoms>
    <comment line>
    <element> <x> <y> <z>
    ...
    
    Args:
        molecule_data: Molecular data in any RDKit-supported format
        
    Returns:
        String in simple XYZ format suitable for ORCA
    """
    if not RDKIT_AVAILABLE:
        # If it looks like XYZ (starts with number), return as is
        lines = molecule_data.strip().split('\n')
        if len(lines) > 2 and lines[0].strip().isdigit():
            return molecule_data
        
        logger.warning("RDKit not available and input does not look like XYZ. Returning data as-is.")
        return molecule_data
    
    try:
        # Try to parse as different formats
        mol = None
        
        # Try SMILES first (simplest)
        if not mol and len(molecule_data.strip().split('\n')) == 1:
            try:
                mol = Chem.MolFromSmiles(molecule_data.strip())
                if mol:
                    # Generate 3D coordinates for SMILES
                    mol = Chem.AddHs(mol)
                    AllChem.EmbedMolecule(mol, randomSeed=42)
                    AllChem.MMFFOptimizeMolecule(mol)
            except:
                pass
        
        # Try SDF/MOL format
        if not mol:
            try:
                mol = Chem.MolFromMolBlock(molecule_data)
            except:
                pass
        
        # Try PDB format
        if not mol:
            try:
                mol = Chem.MolFromPDBBlock(molecule_data)
            except:
                pass
        
        if not mol:
            # If it looks like XYZ, return it
            lines = molecule_data.strip().split('\n')
            if len(lines) > 2 and lines[0].strip().isdigit():
                return molecule_data
                
            logger.error("Could not parse molecular data in any known format")
            return molecule_data
        
        # Get conformer (3D coordinates)
        if mol.GetNumConformers() == 0:
            mol = Chem.AddHs(mol)
            AllChem.EmbedMolecule(mol, randomSeed=42)
            AllChem.MMFFOptimizeMolecule(mol)
        
        conf = mol.GetConformer()
        
        # Build simple XYZ format string
        num_atoms = mol.GetNumAtoms()
        xyz_lines = [str(num_atoms), "Generated by QC Service"]  # Number of atoms and comment line
        
        for i in range(num_atoms):
            atom = mol.GetAtomWithIdx(i)
            pos = conf.GetAtomPosition(i)
            symbol = atom.GetSymbol()
            # Format: Element X Y Z (with proper spacing)
            xyz_lines.append(f"{symbol:2s}  {pos.x:12.8f}  {pos.y:12.8f}  {pos.z:12.8f}")
        
        return "\n".join(xyz_lines)
        
    except Exception as e:
        logger.error(f"Error converting to XYZ format: {e}")
        return molecule_data

def configure_calculator(calc: 'Calculator', params: Dict[str, Any]) -> None:
    """
    Configure an OPI Calculator instance with the provided parameters.
    
    This function follows the OPI tutorial patterns, using proper enum classes
    for DFT methods, basis sets, tasks, etc. instead of raw strings.
    
    Args:
        calc: OPI Calculator instance
        params: Dictionary of job parameters
    """
    if not OPI_AVAILABLE:
        raise ImportError("orca-pi not installed")
    
    # Import validation module for method categorization
    from services.qc.validation import (
        METHODS_WITHOUT_BASIS, normalize_method_name,
        DLPNO_CC_METHODS, CANONICAL_CC_METHODS, COUPLED_CLUSTER_METHODS, CC_AUX_BASIS_MAP
    )
    
    # Extract parameters
    method = params.get('method', 'B3LYP')
    method_upper = normalize_method_name(method)
    
    # For methods that don't use basis sets (xTB, semi-empirical, composite methods),
    # default to empty string if not explicitly provided
    # Based on ORCA Manual Section 7.4
    if method_upper in METHODS_WITHOUT_BASIS:
        basis = params.get('basis_set') or params.get('basis', '')
    else:
        basis = params.get('basis_set') or params.get('basis', 'def2-SVP')
    job_type = params.get('job_type', 'OPT').upper()
    compute_frequencies = params.get('compute_frequencies', False)
    solvation = params.get('solvation')
    calculate_properties = params.get('calculate_properties', True)
    
    # Advanced parameters
    dispersion = params.get('dispersion', 'none')
    use_rijcosx = params.get('use_rijcosx', False)
    scf_convergence = params.get('scf_convergence', 'Normal')
    convergence_strategy = params.get('convergence_strategy', 'DIIS')
    use_slow_conv = params.get('use_slow_conv', False)
    integration_grid = params.get('integration_grid', 'DefGrid2')
    broken_symmetry_atoms = params.get('broken_symmetry_atoms', '')
    properties = params.get('properties', {})
    extra_keywords = params.get('extra_keywords', '')
    freq_scale_factor = params.get('freq_scale_factor', None)

    # Coupled cluster specific parameters
    cc_max_iter = params.get('cc_max_iter', None)         # Max CC iterations (default: ORCA's 50)
    cc_use_qros = params.get('cc_use_qros', False)        # Use QRO orbitals for open-shell
    cc_density = params.get('cc_density', None)           # CC density: none/linearized/unrelaxed/orbopt
    cc_max_diis = params.get('cc_max_diis', None)         # Max DIIS vectors (default: 7)
    cc_level_shift = params.get('cc_level_shift', None)   # Level shift for coefficient updates

    # =========================================================================
    # OPI ENUM MAPPINGS - Map string parameters to proper OPI enum values
    # Following the tutorial pattern for robust configuration
    # Note: We use getattr with None default to handle version differences in OPI
    # =========================================================================
    
    def safe_enum_get(enum_class, attr_name):
        """Safely get an enum attribute, returning None if it doesn't exist."""
        return getattr(enum_class, attr_name, None)
    
    # Build DFT method mapping dynamically to handle OPI version differences
    DFT_METHOD_MAP = {}
    dft_mappings = [
        ('B3LYP', 'B3LYP'),
        ('PBE', 'PBE'),
        ('PBE0', 'PBE0'),
        ('BLYP', 'BLYP'),
        ('BP86', 'BP86'),
        ('M062X', 'M062X'),
        ('TPSS', 'TPSS'),
        ('TPSSH', 'TPSSH'),
        ('WB97X', 'WB97X'),
        ('WB97X-D3', 'WB97XD3'),
        ('WB97X-D4', 'WB97XD4'),
        ('CAM-B3LYP', 'CAMB3LYP'),
        ('R2SCAN', 'R2SCAN'),
    ]
    for key, attr in dft_mappings:
        val = safe_enum_get(Dft, attr)
        if val is not None:
            DFT_METHOD_MAP[key] = val
    
    # Build basis set mapping dynamically
    BASIS_SET_MAP = {}
    basis_mappings = [
        ('def2-SVP', 'DEF2_SVP'),
        ('def2-TZVP', 'DEF2_TZVP'),
        ('def2-TZVPP', 'DEF2_TZVPP'),
        ('def2-QZVP', 'DEF2_QZVP'),
        ('cc-pVDZ', 'CC_PVDZ'),
        ('cc-pVTZ', 'CC_PVTZ'),
        ('cc-pVQZ', 'CC_PVQZ'),
        ('aug-cc-pVDZ', 'AUG_CC_PVDZ'),
        ('aug-cc-pVTZ', 'AUG_CC_PVTZ'),
        ('6-31G', 'G_6_31G'),
        ('6-31G*', 'G_6_31GS'),
        ('6-31G**', 'G_6_31GSS'),
        ('6-311G**', 'G_6_311GSS'),
        ('STO-3G', 'STO_3G'),
    ]
    for key, attr in basis_mappings:
        val = safe_enum_get(BasisSet, attr)
        if val is not None:
            BASIS_SET_MAP[key] = val
    
    # Build auxiliary basis set mapping dynamically
    AUX_BASIS_MAP = {}
    aux_mappings = [
        ('def2/J', 'DEF2_J'),
        ('def2-J', 'DEF2_J'),
        ('def2/JK', 'DEF2_JK'),
        ('def2-JK', 'DEF2_JK'),
        ('cc-pVDZ/C', 'CC_PVDZ_C'),
        ('cc-pVTZ/C', 'CC_PVTZ_C'),
        ('aug-cc-pVDZ/C', 'AUG_CC_PVDZ_C'),
    ]
    for key, attr in aux_mappings:
        val = safe_enum_get(AuxBasisSet, attr)
        if val is not None:
            AUX_BASIS_MAP[key] = val
    
    # Build dispersion correction mapping dynamically
    DISPERSION_MAP = {}
    disp_mappings = [
        ('D3', 'D3'),
        ('D3BJ', 'D3BJ'),
        ('D4', 'D4'),
    ]
    for key, attr in disp_mappings:
        val = safe_enum_get(DispersionCorrection, attr)
        if val is not None:
            DISPERSION_MAP[key] = val
    
    # =========================================================================
    # BUILD KEYWORD LIST USING OPI ENUMS
    # =========================================================================
    
    # Add method - try enum first, fallback to SimpleKeyword
    method_upper = method.upper()
    if method_upper in DFT_METHOD_MAP:
        calc.input.add_simple_keywords(DFT_METHOD_MAP[method_upper])
    else:
        # Fallback for methods not in our map (e.g., HF, PM3, composite methods)
        calc.input.add_simple_keywords(SimpleKeyword(method))
    
    # Add basis set - try enum first, fallback to SimpleKeyword
    if basis:
        basis_key = basis.replace('_', '-')  # Normalize
        if basis_key in BASIS_SET_MAP:
            calc.input.add_simple_keywords(BASIS_SET_MAP[basis_key])
        else:
            calc.input.add_simple_keywords(SimpleKeyword(basis))
    
    # =========================================================================
    # COUPLED CLUSTER HANDLING
    # =========================================================================
    is_cc_method = method_upper in COUPLED_CLUSTER_METHODS
    is_dlpno_cc = method_upper in DLPNO_CC_METHODS
    is_canonical_cc = method_upper in CANONICAL_CC_METHODS

    if is_dlpno_cc:
        # Auto-add /C auxiliary basis for DLPNO correlation fitting if not already in extra_keywords
        aux_c_basis = None
        if basis and basis in CC_AUX_BASIS_MAP:
            aux_c_basis = CC_AUX_BASIS_MAP[basis]
        elif basis:
            aux_c_basis = f"{basis}/C"

        if aux_c_basis:
            extra_kws_upper = (extra_keywords or '').upper()
            if '/C' not in extra_kws_upper:
                calc.input.add_simple_keywords(SimpleKeyword(aux_c_basis))
                logger.info(f"Auto-added /C auxiliary basis '{aux_c_basis}' for DLPNO method")

    if is_cc_method:
        # TightSCF is strongly recommended for CC calculations
        if scf_convergence == 'Normal':
            scf_convergence = 'Tight'
            logger.info("Upgraded SCF convergence to TightSCF for coupled cluster calculation")

        # Canonical CC: disable RIJCOSX (it's for exchange fitting, not CC)
        if is_canonical_cc:
            use_rijcosx = False

        # CCSD(T) analytic 2nd derivatives (FREQ) require NoFrozenCore in ORCA.
        # Without it ORCA raises: "AutoCI analytic 2nd derivative can only run with 'NoFrozenCore'"
        if 'FREQ' in job_type or compute_frequencies:
            calc.input.add_simple_keywords(SimpleKeyword('NoFrozenCore'))
            logger.info("Added NoFrozenCore for CC frequency/analytic-gradient calculation")

    # Job type - use Task enum for FREQ (analytical frequencies, as per tutorial)
    if job_type == 'OPTTS':
        calc.input.add_simple_keywords(SimpleKeyword('OptTS'))
    elif 'OPT' in job_type:
        calc.input.add_simple_keywords(Task.OPT)
    
    # FREQ task - use Task.FREQ for analytical frequencies (following the tutorial)
    # This is faster and preferred over NumFreq
    if 'FREQ' in job_type or compute_frequencies:
        calc.input.add_simple_keywords(Task.FREQ)

        # Add BlockFreq for frequency scaling if specified
        # The tutorial uses BlockFreq(scalfreq=0.970) for scaling
        if freq_scale_factor:
            freq_block = BlockFreq(scalfreq=float(freq_scale_factor))
            calc.input.add_blocks(freq_block)
    
    # Dispersion correction - use enum
    # Based on ORCA Manual Section 7.4.2.8
    # Skip dispersion for methods that already include it or don't support it
    from services.qc.validation import (
        FUNCTIONALS_WITH_BUILTIN_DISPERSION, 
        XTB_METHODS, 
        SEMIEMPIRICAL_METHODS,
        COMPOSITE_METHODS,
        HYBRID_FUNCTIONALS,
        PURE_GGA_FUNCTIONALS
    )
    
    should_add_dispersion = (
        dispersion and
        dispersion.upper() not in ('', 'NONE') and
        method_upper not in FUNCTIONALS_WITH_BUILTIN_DISPERSION and
        method_upper not in XTB_METHODS and
        method_upper not in SEMIEMPIRICAL_METHODS and
        method_upper not in COMPOSITE_METHODS and
        not is_cc_method  # Dispersion corrections don't apply to wavefunction/CC methods
    )
    
    if should_add_dispersion:
        if dispersion.upper() in DISPERSION_MAP:
            calc.input.add_simple_keywords(DISPERSION_MAP[dispersion.upper()])
        else:
            calc.input.add_simple_keywords(SimpleKeyword(dispersion))
    
    # RIJCOSX approximation - use Approximation enum
    # Based on ORCA Manual Section 7.4.2.6
    # RIJCOSX is beneficial for hybrid functionals and HF, but not for
    # pure GGA, semiempirical, or xTB methods
    should_use_rijcosx = use_rijcosx
    
    # Skip RIJCOSX for methods where it's not applicable
    if method_upper in XTB_METHODS or method_upper in SEMIEMPIRICAL_METHODS or method_upper in COMPOSITE_METHODS:
        should_use_rijcosx = False
    elif ('FREQ' in job_type or compute_frequencies) and not use_rijcosx:
        # Enable RIJCOSX by default for frequency calculations with hybrid functionals
        if method_upper in HYBRID_FUNCTIONALS or method_upper == 'HF':
            should_use_rijcosx = True
    
    if should_use_rijcosx:
        calc.input.add_simple_keywords(Approximation.RIJCOSX)
        # Add auxiliary basis set (def2/J is standard for most basis sets)
        calc.input.add_simple_keywords(AuxBasisSet.DEF2_J)
    
    # SCF Convergence
    if scf_convergence == 'Tight':
        calc.input.add_simple_keywords(SimpleKeyword('TightSCF'))
    elif scf_convergence == 'VeryTight':
        calc.input.add_simple_keywords(SimpleKeyword('VeryTightSCF'))
    elif scf_convergence == 'Loose':
        calc.input.add_simple_keywords(SimpleKeyword('LooseSCF'))
    
    # Convergence Strategy - only add if explicitly requested
    # NOTE: Do NOT add SOSCF by default as it can cause convergence problems for large molecules
    if convergence_strategy == 'KDIIS':
        calc.input.add_simple_keywords(SimpleKeyword('KDIIS'))
    elif convergence_strategy == 'SOSCF':
        calc.input.add_simple_keywords(SimpleKeyword('SOSCF'))
    elif convergence_strategy == 'NR':
        calc.input.add_simple_keywords(SimpleKeyword('NR'))
    
    # SlowConv helps with difficult molecules - enable by default for large molecules
    # or when explicitly requested
    if use_slow_conv:
        calc.input.add_simple_keywords(SimpleKeyword('SlowConv'))
    
    # NOTE: Removed automatic SOSCF - it was causing SCF convergence failures
    # For difficult molecules, use SlowConv or explicit %scf block settings instead
    
    # Integration Grid
    if integration_grid == 'DefGrid3':
        calc.input.add_simple_keywords(SimpleKeyword('DefGrid3'))
    elif integration_grid == 'GridX':
        calc.input.add_simple_keywords(SimpleKeyword('GridX'))
    
    # Broken Symmetry
    if broken_symmetry_atoms:
        atom_indices = broken_symmetry_atoms.strip().replace(',', ' ').split()
        if atom_indices:
            calc.input.add_simple_keywords(SimpleKeyword(f"FlipSpin({','.join(atom_indices)})"))
    
    # Properties
    # For CC methods, CHELPG/Mulliken/PrintGap/KeepDens require a CC density to be meaningful.
    # Without explicitly requesting density (cc_density != None/none), these are silently skipped.
    cc_density_requested = bool(
        is_cc_method and cc_density and cc_density.lower() not in ('none', '')
    )

    added_keywords = set()
    if properties:
        if properties.get('dipole', False):
            calc.input.add_simple_keywords(SimpleKeyword('Dipole'))
        if properties.get('quadrupole', False):
            calc.input.add_simple_keywords(SimpleKeyword('Quadrupole'))
        if properties.get('chelpg', False):
            if 'chelpg' not in added_keywords and (not is_cc_method or cc_density_requested):
                calc.input.add_simple_keywords(SimpleKeyword('CHELPG'))
                added_keywords.add('chelpg')
        if properties.get('mulliken', False):
            if not is_cc_method or cc_density_requested:
                calc.input.add_simple_keywords(SimpleKeyword('Mulliken'))
        if properties.get('bond_orders', False):
            calc.input.add_simple_keywords(SimpleKeyword('Mayer'))
        if properties.get('nbo', False):
            calc.input.add_simple_keywords(SimpleKeyword('NBO'))
        if properties.get('nmr', False):
            calc.input.add_simple_keywords(SimpleKeyword('NMR'))
        if properties.get('td_dft', False):
            roots = properties.get('td_dft_roots', 5)
            calc.input.add_simple_keywords(SimpleKeyword(f'TD-DFT({roots})'))
        if properties.get('orbitals', False):
            if 'printgap' not in added_keywords and not is_cc_method:
                calc.input.add_simple_keywords(SimpleKeyword('PrintGap'))
                added_keywords.add('printgap')
            if 'keepdens' not in added_keywords and not is_cc_method:
                calc.input.add_simple_keywords(SimpleKeyword('KeepDens'))
                added_keywords.add('keepdens')
    elif calculate_properties and not is_cc_method:
        # Default DFT/HF properties — skipped for CC (not meaningful without CC density)
        if 'chelpg' not in added_keywords:
            calc.input.add_simple_keywords(SimpleKeyword('CHELPG'))
            added_keywords.add('chelpg')
        if 'printgap' not in added_keywords:
            calc.input.add_simple_keywords(SimpleKeyword('PrintGap'))
            added_keywords.add('printgap')
        if 'keepdens' not in added_keywords:
            calc.input.add_simple_keywords(SimpleKeyword('KeepDens'))
            added_keywords.add('keepdens')
            
    # Extra keywords
    if extra_keywords:
        extras = extra_keywords.replace('!', '').split()
        for kw in extras:
            kw_lower = kw.lower()
            if kw_lower not in added_keywords:
                # Skip freq/numfreq if already added via Task.FREQ
                if kw_lower in ['freq', 'numfreq'] and ('FREQ' in job_type or compute_frequencies):
                    continue
                calc.input.add_simple_keywords(SimpleKeyword(kw))
                added_keywords.add(kw_lower)

    # Solvation
    if solvation:
        cpcm_block = BlockCpcm()
        cpcm_block.smd = True
        cpcm_block.solvent = solvation.lower()
        calc.input.add_blocks(cpcm_block)

    # Coupled cluster %mdci block settings (stored for post-write injection)
    # We store these on the calculator as a special attribute for use in inject_mdci_settings
    if is_cc_method:
        calc._cc_params = {
            'max_iter': cc_max_iter,
            'use_qros': cc_use_qros,
            'density': cc_density,
            'max_diis': cc_max_diis,
            'level_shift': cc_level_shift,
        }

def compute_fukui_charge(charges1: list[float], charges2: list[float], mode: str) -> list[float]:
    """
    Compute the Fukui function from atomic charges.
    
    f+ (nucleophilic attack): rho(N+1) - rho(N)
    f- (electrophilic attack): rho(N) - rho(N-1)
    f0 (radical attack): 1/2 [rho(N+1) - rho(N-1)]
    
    Note: Employing Mulliken charges instead of populations/densities introduces a minus sign.
    """
    import numpy as np
    
    q1 = np.array(charges1)
    q2 = np.array(charges2)
    
    # Reverted order due to using charges instead of populations/densities
    if mode == 'plus/minus':
        diff_charge = (q2 - q1)
    elif mode == 'zero':
        diff_charge = (q2 - q1) / 2
    else:
        raise ValueError(f"Unknown mode: {mode}")
        
    return diff_charge.tolist()

def generate_preview(params: Dict[str, Any]) -> str:
    """
    Generate the ORCA input file content as a string for preview.
    
    Args:
        params: Job parameters
        
    Returns:
        String containing the generated input file content
    """
    if not OPI_AVAILABLE:
        return "# Error: orca-pi library not installed on backend"

    try:
        # Create a dummy calculator
        # We don't need a real working dir for preview, but Calculator might require one
        calc = Calculator(basename="preview", working_dir="/tmp")
        
        # Configure it
        configure_calculator(calc, params)
        
        # Resources (defaults for preview)
        n_procs = int(params.get('n_procs') or QCConfig.DEFAULT_N_PROCS)
        memory_mb = int(params.get('memory_mb') or QCConfig.DEFAULT_MEMORY_MB)
        memory_per_core = memory_mb // n_procs
        
        calc.input.ncores = n_procs
        calc.input.maxcore = memory_per_core
        
        # Structure
        molecule_data = params.get('molecule_xyz', '')
        charge = int(params.get('charge') or 0)
        mult = int(params.get('multiplicity') or 1)
        
        if molecule_data:
            xyz_string = convert_to_simple_xyz(molecule_data)
            # We can't easily create a Structure object without a file in OPI
            # But we can mock the structure block in the output string
            
            # OPI's Calculator.input.render() or similar might be what we want
            # But OPI seems to write files.
            # Let's manually construct the string using OPI's components where possible
            
            # OPI doesn't seem to have a simple "render to string" for the whole input
            # It has write_input() which writes to file.
            
            # We can use a temporary file approach
            import tempfile
            with tempfile.TemporaryDirectory() as tmpdir:
                tmp_path = Path(tmpdir)
                calc.working_dir = tmp_path
                
                # Write XYZ to file so Structure can read it
                xyz_file = tmp_path / "input.xyz"
                xyz_file.write_text(xyz_string)
                
                structure = Structure.from_xyz(str(xyz_file))
                structure.charge = charge
                structure.multiplicity = mult
                calc.structure = structure
                
                # Write input
                calc.write_input()
                
                # Read back
                inp_file = tmp_path / "preview.inp"
                if inp_file.exists():
                    return inp_file.read_text()
                else:
                    return "# Error: Failed to generate input file"
        else:
            return "# Error: No molecule data provided"
            
    except Exception as e:
        logger.error(f"Error generating preview: {e}")
        return f"# Error generating preview: {str(e)}"


def inject_robust_scf_settings(input_file_path: str, n_atoms: int = 0) -> None:
    """
    Inject robust SCF settings into the ORCA input file for difficult molecules.
    
    This function adds a %scf block with level shifting and damping to help
    with SCF convergence for larger molecules (~30+ atoms) or challenging
    electronic structures.
    
    Args:
        input_file_path: Path to the ORCA .inp file
        n_atoms: Number of atoms in the molecule (used to adjust settings)
    """
    from pathlib import Path
    
    input_path = Path(input_file_path)
    if not input_path.exists():
        logger.warning(f"Input file not found for SCF injection: {input_file_path}")
        return
    
    try:
        content = input_path.read_text()
        
        # Check if there's already a %scf block
        if '%scf' in content.lower():
            logger.info("SCF block already present in input file, skipping injection")
            return
        
        # Build SCF block with robust settings for larger molecules
        # These settings help with oscillating SCF and convergence issues:
        # - MaxIter: More iterations to allow convergence
        # - DampFac: Damping to prevent oscillations (0.7 is more conservative)
        # - Shift: Level shift to improve HOMO-LUMO gap and convergence
        # - ShiftEnd: Turn off shift when close to convergence
        # - DIISMaxEq: More DIIS vectors for better extrapolation
        scf_block = """
%scf
    MaxIter 300
    DampFac 0.7
    DampErr 0.1
    Shift Shift 0.1 ErrOff 0.1 end
    DIISMaxEq 15
    DirectResetFreq 1
end
"""
        
        # Find a good place to insert the SCF block
        # We want it after the simple keywords but before any other blocks
        lines = content.split('\n')
        insert_idx = 0
        
        # Find the last simple keyword line (lines starting with !)
        for i, line in enumerate(lines):
            if line.strip().startswith('!'):
                insert_idx = i + 1
        
        # If there's a %pal or %output block before our insert point, insert before them
        # Actually, let's just insert after all the ! keywords
        for i, line in enumerate(lines):
            stripped = line.strip().lower()
            if stripped.startswith('%') and i > insert_idx:
                # Found a block, insert SCF block before it
                insert_idx = i
                break
        
        # Insert the SCF block
        lines.insert(insert_idx, scf_block)
        new_content = '\n'.join(lines)
        
        input_path.write_text(new_content)
        logger.info(f"Injected robust SCF settings into {input_file_path}")
        
    except Exception as e:
        logger.error(f"Error injecting SCF settings: {e}")


def inject_robust_scf_settings_fukui(input_file_path: str, charge: int, multiplicity: int, aggressive: bool = False) -> None:
    """
    Inject charge-aware robust SCF settings for Fukui calculations.
    
    Fukui calculations involve neutral, anionic, and cationic species that often
    have convergence difficulties, especially anions with small HOMO-LUMO gaps.
    
    This function applies different settings based on charge:
    - Anions (charge < 0): Huckel guess, higher damping, level shifting
    - Cations (charge > 0): PAtom guess, moderate damping
    - Neutral (charge == 0): Standard robust settings
    
    Args:
        input_file_path: Path to the ORCA .inp file
        charge: Molecular charge (negative for anions, positive for cations)
        multiplicity: Spin multiplicity
        aggressive: If True, use more aggressive settings for difficult cases
    """
    from pathlib import Path
    
    input_path = Path(input_file_path)
    if not input_path.exists():
        logger.warning(f"Input file not found for Fukui SCF injection: {input_file_path}")
        return
    
    try:
        content = input_path.read_text()
        
        # Check if there's already a %scf block - if so, we'll enhance it
        has_scf_block = '%scf' in content.lower()
        
        # Determine settings based on charge and aggressiveness
        if aggressive:
            max_iter = 500
            damp_fac = 0.9
            shift_value = 0.3
            diis_max_eq = 20
        else:
            max_iter = 300
            damp_fac = 0.7 if charge < 0 else 0.75  # More damping for anions
            shift_value = 0.15 if charge < 0 else 0.1  # More level shift for anions
            diis_max_eq = 15
        
        # Determine initial guess based on charge
        guess_type = None
        if charge < 0:
            # Anions benefit from Huckel guess
            guess_type = "Huckel"
        elif charge > 0:
            # Cations benefit from PAtom guess
            guess_type = "PAtom"
        # Neutral species use default guess (don't specify)
        
        # Build SCF block with charge-aware settings
        scf_lines = [
            "%scf",
            f"    MaxIter {max_iter}",
            f"    DampFac {damp_fac}",
            "    DampErr 0.1",
            f"    Shift Shift {shift_value} ErrOff 0.1 end",
            f"    DIISMaxEq {diis_max_eq}",
            "    DirectResetFreq 1"
        ]
        
        scf_lines.append("end")
        scf_block = "\n".join(scf_lines) + "\n"
        
        if has_scf_block:
            # Enhance existing SCF block
            logger.info(f"Enhancing existing SCF block for Fukui calculation (charge={charge}, mult={multiplicity})")
            
            # Find and replace the %scf block
            lines = content.split('\n')
            scf_start = -1
            scf_end = -1
            
            for i, line in enumerate(lines):
                if line.strip().lower().startswith('%scf'):
                    scf_start = i
                elif scf_start >= 0 and line.strip().lower() == 'end':
                    scf_end = i
                    break
            
            if scf_start >= 0 and scf_end >= 0:
                # Replace existing block
                new_lines = lines[:scf_start] + scf_block.split('\n') + lines[scf_end+1:]
                new_content = '\n'.join(new_lines)
            else:
                # Couldn't find end, just append
                logger.warning("Could not find end of existing SCF block, appending instead")
                new_content = content + "\n" + scf_block
        else:
            # Insert new SCF block
            lines = content.split('\n')
            insert_idx = 0
            
            # Find the last simple keyword line (lines starting with !)
            for i, line in enumerate(lines):
                if line.strip().startswith('!'):
                    insert_idx = i + 1
            
            # Find first % block to insert before it
            for i, line in enumerate(lines):
                stripped = line.strip().lower()
                if stripped.startswith('%') and i > insert_idx:
                    insert_idx = i
                    break
            
            # Insert the SCF block
            lines.insert(insert_idx, scf_block)
            new_content = '\n'.join(lines)
        
        input_path.write_text(new_content)
        logger.info(f"Injected robust Fukui SCF settings (charge={charge}, mult={multiplicity}, aggressive={aggressive}) into {input_file_path}")
        
    except Exception as e:
        logger.error(f"Error injecting Fukui SCF settings: {e}", exc_info=True)


def inject_mdci_settings(input_file_path: str, cc_params: dict) -> None:
    """
    Inject a %mdci block into the ORCA input file for coupled cluster settings.

    Controls CCSD/DLPNO-CC convergence and properties:
    - MaxIter: Maximum CC iterations (ORCA default: 50)
    - MaxDIIS: Maximum DIIS vectors (ORCA default: 7; increase for difficult convergence)
    - Lshift: Level shift for coefficient updates (ORCA default: 0.2)
    - UseQROs: Transform UHF orbitals to quasi-restricted (recommended for open-shell DLPNO)
    - density: Type of CC density to compute (none/linearized/unrelaxed/orbopt)

    Args:
        input_file_path: Path to the ORCA .inp file
        cc_params: Dictionary with CC-specific parameters (max_iter, use_qros, density,
                   max_diis, level_shift)
    """
    from pathlib import Path

    input_path = Path(input_file_path)
    if not input_path.exists():
        logger.warning(f"Input file not found for %mdci injection: {input_file_path}")
        return

    # Check if any CC params are actually set
    max_iter = cc_params.get('max_iter')
    use_qros = cc_params.get('use_qros', False)
    density = cc_params.get('density')
    max_diis = cc_params.get('max_diis')
    level_shift = cc_params.get('level_shift')

    has_anything = any([max_iter, use_qros, density, max_diis, level_shift])
    if not has_anything:
        return

    try:
        content = input_path.read_text()

        # Check if %mdci block already exists
        if '%mdci' in content.lower():
            logger.info("%mdci block already present, skipping injection")
            return

        mdci_lines = ["%mdci"]
        if max_iter is not None:
            mdci_lines.append(f"    MaxIter {int(max_iter)}")
        if max_diis is not None:
            mdci_lines.append(f"    MaxDIIS {int(max_diis)}")
        if level_shift is not None:
            mdci_lines.append(f"    Lshift {float(level_shift):.3f}")
        if use_qros:
            mdci_lines.append("    UseQROs true")
        if density and density.lower() != 'none':
            valid_densities = {'linearized', 'unrelaxed', 'orbopt'}
            if density.lower() in valid_densities:
                mdci_lines.append(f"    density {density.lower()}")
            else:
                logger.warning(f"Unknown CC density type '{density}', skipping")
        mdci_lines.append("end")

        mdci_block = "\n".join(mdci_lines) + "\n"

        # Insert after the last ! keyword line, before any % blocks
        lines = content.split('\n')
        insert_idx = 0
        for i, line in enumerate(lines):
            if line.strip().startswith('!'):
                insert_idx = i + 1
        for i, line in enumerate(lines):
            stripped = line.strip().lower()
            if stripped.startswith('%') and i > insert_idx:
                insert_idx = i
                break

        lines.insert(insert_idx, mdci_block)
        input_path.write_text('\n'.join(lines))
        logger.info(f"Injected %mdci settings into {input_file_path}: {cc_params}")

    except Exception as e:
        logger.error(f"Error injecting %mdci settings: {e}", exc_info=True)
